from fastapi import APIRouter, Depends, Query, Header, HTTPException
from typing import Optional
from app.core.security import get_current_user
from app.services.search_service import (
    get_all_locations_for_dropdown,
    get_all_categories_for_dropdown,
    search_incidents,
)

router = APIRouter()


# ── Dropdown seeders ──────────────────────────────────────────────────────────

@router.get("/locations")
def fetch_locations_for_dropdown(
    current_user: dict = Depends(get_current_user),
):
    """
    Called instantly when user checks the 'location_wise' checkbox.
    Returns distinct (area_name, city, complete_location) pairs
    that have at least one incident — seeds the location dropdown.

    Response:
    {
      "total": 2,
      "locations": [
        {"area_name": "Gulshan",     "city": "Karachi", "complete_location": "Gulshan, Karachi"},
        {"area_name": "Baldia Town", "city": "Karachi", "complete_location": "Baldia Town, Karachi"}
      ]
    }
    """
    return get_all_locations_for_dropdown()


@router.get("/categories")
def fetch_categories_for_dropdown(
    current_user: dict = Depends(get_current_user),
):
    """
    Called instantly when user checks the 'category_wise' checkbox.
    Returns only categories that have at least one incident — seeds the
    category dropdown, sorted by most common first.

    Response:
    {
      "total": 3,
      "categories": [
        {"category_name": "robbery",    "incident_count": 5},
        {"category_name": "theft",      "incident_count": 3},
        {"category_name": "cybercrime", "incident_count": 1}
      ]
    }
    """
    return get_all_categories_for_dropdown()


# ── Main search endpoint ──────────────────────────────────────────────────────

@router.get("/incidents")
def search_incidents_endpoint(

    # ── Checkbox states (which filter modes are active) ───────────────────────
    all_cases: bool = Query(
        False,
        description=(
            "Check this to get ALL incidents regardless of location or category. "
            "When True, overrides location_wise and category_wise entirely."
        )
    ),
    location_wise: bool = Query(
        False,
        description="Check this to filter by location. Requires area_name and city."
    ),
    category_wise: bool = Query(
        False,
        description="Check this to filter by category. Requires category_name."
    ),

    # ── Location values — from /search/locations dropdown ─────────────────────
    area_name: Optional[str] = Query(
        None,
        description=(
            "Required when location_wise=true. "
            "Use the exact area_name value returned by GET /search/locations."
        )
    ),
    city: Optional[str] = Query(
        None,
        description=(
            "Required when location_wise=true. "
            "Use the exact city value returned by GET /search/locations."
        )
    ),

    # ── Category value — from /search/categories dropdown ─────────────────────
    category_name: Optional[str] = Query(
        None,
        description=(
            "Required when category_wise=true. "
            "Use the exact category_name value returned by GET /search/categories."
        )
    ),

    # ── Debounce tracking ─────────────────────────────────────────────────────
    request_id: Optional[str] = Header(
        None,
        alias="X-Request-ID",
        description=(
            "Unique ID generated by frontend per debounced call. "
            "Echoed back in response so frontend can discard stale responses."
        )
    ),

    current_user: dict = Depends(get_current_user),
):
    """
    Unified incident search endpoint supporting all four checkbox cases.

    ── Case 1: all_cases=true ───────────────────────────────────────────────
    Returns every incident ever recorded. Location and category filters
    are completely ignored even if provided.
    Also applies when all three checkboxes are checked simultaneously.

      GET /search/incidents?all_cases=true

    ── Case 2: location_wise=true only ─────────────────────────────────────
    Returns all incidents at the selected location regardless of category.
    area_name and city must match values from GET /search/locations.

      GET /search/incidents?location_wise=true&area_name=Gulshan&city=Karachi

    ── Case 3: category_wise=true only ─────────────────────────────────────
    Returns all incidents of the selected category regardless of location.
    category_name must match a value from GET /search/categories.

      GET /search/incidents?category_wise=true&category_name=robbery

    ── Case 4: location_wise=true AND category_wise=true ───────────────────
    Returns only incidents that match BOTH the selected location AND
    the selected category. Both dropdowns are shown simultaneously.

      GET /search/incidents
        ?location_wise=true&area_name=Gulshan&city=Karachi
        &category_wise=true&category_name=robbery

    ── Response structure ───────────────────────────────────────────────────
    {
      "active_filters": {
        "location_wise": true,
        "area_name": "Gulshan",
        "city": "Karachi",
        "complete_location": "Gulshan, Karachi",
        "category_wise": true,
        "category_name": "robbery"
      },
      "total": 2,
      "results": [ { incident fields... } ],
      "request_id": "abc-123"
    }
    """
    # Reject if no checkbox is checked at all
    if not all_cases and not location_wise and not category_wise:
        raise HTTPException(
            status_code=422,
            detail=(
                "At least one checkbox must be selected: "
                "all_cases, location_wise, or category_wise."
            )
        )

    result = search_incidents(
        all_cases     = all_cases,
        location_wise = location_wise,
        category_wise = category_wise,
        area_name     = area_name,
        city          = city,
        category_name = category_name,
    )

    # Echo request_id back for frontend debounce race-condition handling
    result["request_id"] = request_id

    return result